name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  files:
    description: Glob of files to be PUT to the space
    required: false
  filesStripPrefix:
    description:
      strip this prefix from the beginning of the matched file path relative to
      repo root
    required: false
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Your output description here
  resource:
    description: URL to a resource that was PUT

runs:
  using: node20
  main: dist/index.js
